/**/controller_manager:
  ros__parameters:
    update_rate: 100

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

/**/diff_drive_controller:
  ros__parameters:
    left_wheel_names:
      - left_front_wheel_joint
      - left_rear_wheel_joint
    right_wheel_names:
      - right_front_wheel_joint
      - right_rear_wheel_joint

    wheel_separation: 0.195
    wheel_radius: 0.035
    
    cmd_vel_timeout: 0.5
    publish_rate: 50.0
    
    use_stamped_vel: false

    base_frame_id: base_footprint
    odom_frame_id: odom
    
    publish_odom: true
    enable_odom_tf: true

    pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.1]
    twist_covariance_diagonal: [0.001, 1000000.0, 1000000.0, 1000000.0, 1000000.0, 0.1]